# Generated by Django 3.2.3 on 2021-06-12 16:55

from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
    ]
