# Generated by Django 3.2.3 on 2021-06-12 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 12, 16, 58, 20, 979548, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
